# Generated by Django 2.2.16 on 2023-03-09 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20230310_0231'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='unique_comments',
        ),
    ]
